### ISSUE TITLE
invariances in sift

### ISSUE THREAD

**Issue by micheleAlberto** [ankurhanda/gvnn#2]
"... something not possible with pure geometric methods that either rely on pixel values or SIFT-like features"

Following the sift paper ( [lowe 2004](https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf)) that descriptor should be robust to changes in illuminations because it uses as a low level feature the orientation of (localy sampled) gradients.
SIFT has also been used for many works in [internet photo collections](http://www.cs.cornell.edu/projects/bigsfm/) that use pictures from flikr or other uncontrolled acquisition sources.

Maybe i am not understanding that statement...
(A github issue may not be a good place for a theoretical question)

**Comment by ankurhanda** [comment]
The point here is that if there aren't many interesting features in the scene due to low-resolution of the images or motion blur or if the lighting changes are severe then I don't think feature matching works as well http://tinyurl.com/hpv8g3f. Your only hope of aligning them is via semantics _i.e._ semantic alignment and that was the point I was trying to make.  Also, those features are detected via carefully chosen thresholds which may not be ideal as your lighting in the scene changes across days and nights. 

Sorry for the confusion. I've also changed the README to avoid any more confusion.

**Comment by ankurhanda** [comment]
I've changed the README to avoid any more confusion.
